/*
 * discover lotus positions
 */
#include <Adeept_PWMPCA9685.h>
#include "custom_geometry.h"

// "lotus"
leg_descriptor_t legA_lotus = { {LEGA_CONTROLLER,LEGA_SERVO1_CHANNEL, 45},{LEGA_CONTROLLER,LEGA_SERVO2_CHANNEL,58},{LEGA_CONTROLLER,LEGA_SERVO3_CHANNEL,120} };
leg_descriptor_t legB_lotus = { {LEGB_CONTROLLER,LEGB_SERVO1_CHANNEL, 50},{LEGB_CONTROLLER,LEGB_SERVO2_CHANNEL,58},{LEGB_CONTROLLER,LEGB_SERVO3_CHANNEL,120} };
leg_descriptor_t legC_lotus = { {LEGC_CONTROLLER,LEGC_SERVO1_CHANNEL, 52},{LEGC_CONTROLLER,LEGC_SERVO2_CHANNEL,58},{LEGC_CONTROLLER,LEGC_SERVO3_CHANNEL,120} };
leg_descriptor_t legD_lotus = { {LEGD_CONTROLLER,LEGD_SERVO1_CHANNEL, 55},{LEGD_CONTROLLER,LEGD_SERVO2_CHANNEL,45},{LEGD_CONTROLLER,LEGD_SERVO3_CHANNEL,  0} };
leg_descriptor_t legE_lotus = { {LEGE_CONTROLLER,LEGE_SERVO1_CHANNEL, 35},{LEGE_CONTROLLER,LEGE_SERVO2_CHANNEL,45},{LEGE_CONTROLLER,LEGE_SERVO3_CHANNEL,  0} };
leg_descriptor_t legF_lotus = { {LEGF_CONTROLLER,LEGF_SERVO1_CHANNEL, 55},{LEGF_CONTROLLER,LEGF_SERVO2_CHANNEL,45},{LEGF_CONTROLLER,LEGF_SERVO3_CHANNEL,  0} };
robot_descriptor_t lotus  = { { legA_lotus, legB_lotus, legC_lotus, legD_lotus, legE_lotus, legF_lotus } };

// "rdy"
leg_descriptor_t legA_rdy = { {LEGA_CONTROLLER,LEGA_SERVO1_CHANNEL, 45},{LEGA_CONTROLLER,LEGA_SERVO2_CHANNEL,10},{LEGA_CONTROLLER,LEGA_SERVO3_CHANNEL,8} };
leg_descriptor_t legB_rdy = { {LEGB_CONTROLLER,LEGB_SERVO1_CHANNEL, 50},{LEGB_CONTROLLER,LEGB_SERVO2_CHANNEL,10},{LEGB_CONTROLLER,LEGB_SERVO3_CHANNEL,8} };
leg_descriptor_t legC_rdy = { {LEGC_CONTROLLER,LEGC_SERVO1_CHANNEL, 52},{LEGC_CONTROLLER,LEGC_SERVO2_CHANNEL,10},{LEGC_CONTROLLER,LEGC_SERVO3_CHANNEL,8} };
leg_descriptor_t legD_rdy = { {LEGD_CONTROLLER,LEGD_SERVO1_CHANNEL, 55},{LEGD_CONTROLLER,LEGD_SERVO2_CHANNEL,95},{LEGD_CONTROLLER,LEGD_SERVO3_CHANNEL,110} };
leg_descriptor_t legE_rdy = { {LEGE_CONTROLLER,LEGE_SERVO1_CHANNEL, 35},{LEGE_CONTROLLER,LEGE_SERVO2_CHANNEL,95},{LEGE_CONTROLLER,LEGE_SERVO3_CHANNEL,115} };
leg_descriptor_t legF_rdy = { {LEGF_CONTROLLER,LEGF_SERVO1_CHANNEL, 55},{LEGF_CONTROLLER,LEGF_SERVO2_CHANNEL,100},{LEGF_CONTROLLER,LEGF_SERVO3_CHANNEL,110} };
robot_descriptor_t rdy  = { { legA_rdy, legB_rdy, legC_rdy, legD_rdy, legE_rdy, legF_rdy } };

// "stand"
leg_descriptor_t legA_stand = { {LEGA_CONTROLLER,LEGA_SERVO1_CHANNEL, 45},{LEGA_CONTROLLER,LEGA_SERVO2_CHANNEL,70},{LEGA_CONTROLLER,LEGA_SERVO3_CHANNEL,40} };
leg_descriptor_t legB_stand = { {LEGB_CONTROLLER,LEGB_SERVO1_CHANNEL, 50},{LEGB_CONTROLLER,LEGB_SERVO2_CHANNEL,70},{LEGB_CONTROLLER,LEGB_SERVO3_CHANNEL,40} };
leg_descriptor_t legC_stand = { {LEGC_CONTROLLER,LEGC_SERVO1_CHANNEL, 52},{LEGC_CONTROLLER,LEGC_SERVO2_CHANNEL,70},{LEGC_CONTROLLER,LEGC_SERVO3_CHANNEL,40} };
leg_descriptor_t legD_stand = { {LEGD_CONTROLLER,LEGD_SERVO1_CHANNEL, 55},{LEGD_CONTROLLER,LEGD_SERVO2_CHANNEL,30},{LEGD_CONTROLLER,LEGD_SERVO3_CHANNEL,80} };
leg_descriptor_t legE_stand = { {LEGE_CONTROLLER,LEGE_SERVO1_CHANNEL, 35},{LEGE_CONTROLLER,LEGE_SERVO2_CHANNEL,30},{LEGE_CONTROLLER,LEGE_SERVO3_CHANNEL,80} };
leg_descriptor_t legF_stand = { {LEGF_CONTROLLER,LEGF_SERVO1_CHANNEL, 55},{LEGF_CONTROLLER,LEGF_SERVO2_CHANNEL,30},{LEGF_CONTROLLER,LEGF_SERVO3_CHANNEL,80} };
robot_descriptor_t stand  = { { legA_stand, legB_stand, legC_stand, legD_stand, legE_stand, legF_stand } };


// executed once at startup
void setup() {
  pwm0.begin();
  pwm0.setPWMFreq(PWM_SERVO_FREQUENCY);
  pwm1.begin();
  pwm1.setPWMFreq(PWM_SERVO_FREQUENCY);
  //resetRobot();  
  setRobot(rdy);
}

// called continuously at runtime
void loop() {           
  delay(200);  
  
}
